repository:
  name: gha-gcp-opentofu
  description: State bucket and access resources for managing OpenTofu IaC via GitHub Actions
  # default_branch: main TODO restore test
  default_branch: 19-apply-branch-and-tag-protection-settings

  # Prevent strategies other than basic merge, as they interfere with conventional changelog version inference
  allow_squash_merge: false
  allow_rebase_merge: false
  # Instead, merge by merge commit
  allow_merge_commit: true
  # Clean up branches when PRs merge
  delete_branch_on_merge: true

rulesets:
  - name: Tags rules
    target: tag
    enforcement: active
    conditions:
      ref_name:
        include:
          - "~ALL"
        exclude: []
    rules:
      - type: creation
      - type: deletion
      - type: non_fast_forward
      - type: update
  - name: Default branch rules
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "~DEFAULT_BRANCH"
        exclude: []
    bypass_actors:
      - actor_id: 5
        actor_type: RepositoryRole
        bypass_mode: pull_request
    rules:
      - type: creation
      - type: deletion
      - type: non_fast_forward
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: true
          require_last_push_approval: false
          required_approving_review_count: 1
          required_review_thread_resolution: true
      - type: workflows
        parameters:
          workflows:
            - path: .github/workflows/push-workflow.yaml
              repository_id: 863557021

collaborators: [] # No collaborators defined
